version: '3.7' 

services:
  app:
    build:
    ports:
      - "3000:3000"
    depends_on:
      - db 
     environment: 
      DATABASE_URL: postgres://postgres:ayush@db:5432/my_new_database 

  db:
    image: postgres:14-alpine 
    environment:
      POSTGRES_USER: postgres     
      POSTGRES_PASSWORD: ayush      
    volumes:
      - ./database_data:/var/lib/postgresql/data  #  Persistent data volume for PostgreSQL
